version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    env_file:
      - .env
    ports:
      - "7000:7000"
    deploy:
      resources:
        limits:
          cpus: "1.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    env_file:
      - .env
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          cpus: "0.5"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
